<?xml version="1.0" encoding="UTF-8"?>
<tileset name="A4" tilewidth="16" tileheight="16" tilecount="960" columns="32">
 <image source="A4.png" width="512" height="480"/>
 <tile id="0" type="solid"/>
 <tile id="1" type="solid"/>
 <tile id="2" type="solid"/>
 <tile id="3" type="solid"/>
 <tile id="32" type="solid"/>
 <tile id="33" type="solid"/>
 <tile id="34" type="solid"/>
 <tile id="35" type="solid"/>
 <tile id="64" type="solid"/>
 <tile id="65" type="solid"/>
 <tile id="66" type="solid"/>
 <tile id="67" type="solid"/>
 <tile id="96" type="solid"/>
 <tile id="97" type="solid"/>
 <tile id="98" type="solid"/>
 <tile id="99" type="solid"/>
 <tile id="128" type="solid"/>
 <tile id="129" type="solid"/>
 <tile id="130" type="solid"/>
 <tile id="131" type="solid"/>
 <tile id="160" type="solid"/>
 <tile id="161" type="solid"/>
 <tile id="162" type="solid"/>
 <tile id="163" type="solid"/>
 <tile id="192" type="solid"/>
 <tile id="193" type="solid"/>
 <tile id="194" type="solid"/>
 <tile id="195" type="solid"/>
 <tile id="196" type="solid"/>
 <tile id="197" type="solid"/>
 <tile id="198" type="solid"/>
 <tile id="199" type="solid"/>
 <tile id="224" type="solid"/>
 <tile id="225" type="solid"/>
 <tile id="226" type="solid"/>
 <tile id="227" type="solid"/>
 <tile id="228" type="solid"/>
 <tile id="229" type="solid"/>
 <tile id="230" type="solid"/>
 <tile id="231" type="solid"/>
 <tile id="256" type="solid"/>
 <tile id="257" type="solid"/>
 <tile id="258" type="solid"/>
 <tile id="259" type="solid"/>
 <tile id="260" type="solid"/>
 <tile id="261" type="solid"/>
 <tile id="262" type="solid"/>
 <tile id="263" type="solid"/>
 <tile id="288" type="solid"/>
 <tile id="289" type="solid"/>
 <tile id="290" type="solid"/>
 <tile id="291" type="solid"/>
 <tile id="292" type="solid"/>
 <tile id="293" type="solid"/>
 <tile id="294" type="solid"/>
 <tile id="295" type="solid"/>
</tileset>
